### ISSUE TITLE
Comparison to cordova-plugin-firebase?

### ISSUE THREAD

**Issue by janpio** [jsayol/cordova-plugin-firebase-sdk#1]
How does this compare to [cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase)?

**Comment by jsayol** [comment]
Hi @piotrowski! Good question. The main thing to keep in mind:
### This plugin (cordova-plugin-firebase-sdk) currently only works on Android. It's still a work in progress and not ready to use.

Besides that, here's a handy comparison table:

| Firebase component | cordova-plugin-firebase-sdk | cordova-plugin-firebase |
| ---------------------- | :-----------------------------: | :--------------------------: |
| Realtime Database | ✔️ | ❌ |
| Authentication | ✔️ | ❌ |
| Remote Config | ✔️ | ✔️ |
| Cloud Messaging | ✔️ | ✔️ |
| Crash Reporting | ✔️ | ✔️ |
| Analytics | ✔️ | ✔️ |

**Comment by janpio** [comment]
Thanks!

Maybe add this table to the README - cordova-plugin-firebase is used quite often so many people will have this question I think.

**Comment by jsayol** [comment]
That's a good idea 👍 As soon as the plugin is ready and works both on Android and iOS, I will add it. Thanks!
