### ISSUE TITLE
How to check if user is logged in or logged out at startup?

### ISSUE THREAD

**Issue by rajatsawant** [jsayol/cordova-plugin-firebase-sdk#2]
At startup, 
`
        firebase.auth().onAuthStateChanged(function(user){});
`
gives a callback only if user is logged in. Please show the way.

**Comment by jsayol** [comment]
Hi @rajatsawant, thanks for giving this plugin a try but it's not being maintained anymore. It was just an experiment and was never properly tested so I'd suggest not to use it on a production app.
