### ISSUE TITLE
 Congratulations, the project is getting very good.

### ISSUE THREAD

**Issue by douglaszaltron** [jsayol/cordova-plugin-firebase-sdk#3]
Very interesting project, what would be better, is to separate the modules, for future maintenance and implementation for ios, easier to maintain in the community and have a separate implementation. "Write programs that do one thing and do it well." =D
cordova-plugin-firebase-sdk-core
cordova-plugin-firebase-sdk-auth
cordova-plugin-firebase-sdk-database
cordova-plugin-firebase-sdk-messaging
cordova-plugin-firebase-sdk-remoteconfig
cordova-plugin-firebase-sdk-storage
cordova-plugin-firebase-sdk-crash
cordova-plugin-firebase-sdk-analytics

**Comment by jsayol** [comment]
Hi @douglaszaltron, thanks for your suggestions! This plugin is not being maintained anymore, though. It was just an experiment and was never properly tested so I'd suggest not to use it anyway.
