### ISSUE TITLE
It doesn't except the .info path in Firebase Database

### ISSUE THREAD

**Issue by jdiderik** [jsayol/cordova-plugin-firebase-sdk#4]
I use the .info/connected path for presence detection and it fails with the message 
 Invalid path: ".info/connected". Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]"
Maybe an exception should be made for the .info path of firebase

**Comment by jsayol** [comment]
Hi @jdiderik, thanks for giving this plugin a try but it's not being maintained anymore. It was just an experiment and was never properly tested so I'd suggest not to use it on a production app.
